#!/usr/bin/env bash
# shellcheck disable=SC2034

RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
BLUE=$(tput setaf 4)
GREY=$(tput setaf 8)
LIGHTBLUE=$(tput setaf 153)
ORANGE=$(tput setaf 208)
NC=$(tput sgr0) # No Colour
