#!/usr/bin/env bash

menu() {
	local tasks task i=0 input x_option
	local -r desc_width=$(get_longest_task_desc)
	local -r desc_padding=6
	local -r option_padding=2

	mapfile -t tasks <<<"$1"

	echo

	for task in "${tasks[@]}"; do
		print_option "$((++i))" "$option_padding" ": $("$task":describe)" $((desc_width+desc_padding))
	done | column
	
	if [[ $("${tasks[0]}":menu) = "MAIN_MENU" ]]; then
		x_option="Exit"
	else
		x_option="Back"
	fi
	print_option "x" 2 ": $x_option"

	input=$(prompt "Input selection")

	if ((input > 0 && input <= ${#tasks[@]})); then
		# Execute task in a subshell.
		(${tasks[$((input - 1))]})
	elif [[ $input =~ ^[xX]$ ]]; then
		exit
	else
		print_warning "Invalid selection: '$input'"
	fi

	menu "$@"
}
