#!/usr/bin/env bash

source ./task-functions
source ./colours

get_exported_tasks() {
	tasks:filter NO-RUNNER
}

runner:has_task() {
	[[ $1 ]] && grep -Fxq -- "$1" <<<"$(get_exported_tasks)"
}

runner:help() {
	local -r tasks=$(get_exported_tasks)
	local task longest_task_name
	local -r padding=2

	cat <<-.
		${BLUE}usage:$NC '$0' <task> [arg]...

		${BLUE}These tasks are available:$NC

	.

	longest_task_name=$(get_longest_task_name)

	while read -r task; do
		print_option "$task" "$((-(longest_task_name+padding)))" " $("$task":describe)"
	done < <(sort <<<"$tasks")
	echo
}
